default_stages:
  - pre-commit

exclude: "(^CHANGELOG.md$|^openspec|^uv.lock$)"

repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        description: Run ruff format
        language: system
        entry: uv run ruff format
        pass_filenames: true
        types: [python]

      - id: ruff-ckeck
        name: ruff check
        description: Run ruff check
        language: system
        entry: uv run ruff check
        pass_filenames: true
        types: [python]

      - id: zuban-check
        name: zuban check
        description: Run zuban check
        entry: uv run zuban check
        language: system
        pass_filenames: true
        types: [python]

      - id: lint-imports
        name: lint-imports
        description: Run lint-imports
        entry: uv run lint-imports
        language: system
        pass_filenames: false
        types: [python]

      - id: tombi-format
        name: tombi format
        description: Run tombi format
        language: system
        entry: uv run tombi format
        pass_filenames: true
        types: [toml]

      - id: sqlfluff-format
        name: sqlfluff format
        description: Format SQL files with sqlfluff
        language: system
        entry: uv run sqlfluff format --dialect postgres
        pass_filenames: true
        types: [sql]

      - id: sqlfluff-lint
        name: sqlfluff lint
        description: Lint SQL files with sqlfluff
        language: system
        entry: uv run sqlfluff lint --dialect postgres
        pass_filenames: true
        types: [sql]

      - id: mdlint-format
        name: mdlint format
        description: "Run 'mdlint format' for consistent, reliable Markdown formatting."
        entry: uv run mdlint format
        language: system
        types: [markdown]
        args: []

      - id: mdlint-check
        name: mdlint check
        description: "Run 'mdlint check' for consistent, reliable Markdown linting."
        entry: uv run mdlint check
        language: system
        types: [markdown]
        args: []
