---
# yamllint disable rule:line-length
name: Push action

on:
  push:
    branches:
      - master

permissions:
  contents: read # access to check out code and install dependencies

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  release:
    name: Bump version and create draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv pip install -e .[release]

      - name: Create bump and changelog
        id: cz
        if: github.repository == 'tilde-lab/yascheduler'
        uses: commitizen-tools/commitizen-action@e41bf7f2029bc8175af362badd6fd0860a329b0f
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: .CHANGELOG-CURRENT.md
          push: true
          commit: true

      - name: Print new version
        if: github.repository == 'tilde-lab/yascheduler'
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

      - name: Build
        run: flit build

      - name: Stop if no bump
        id: no-bump
        continue-on-error: true
        # will fail if not on exact tag
        run: git describe --tags --exact-match

      - name: Create Release Draft
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        if: steps.no-bump.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: v${{ steps.cz.outputs.version }}
          body_path: .CHANGELOG-CURRENT.md
          fail_on_unmatched_files: true
          files: dist/*
