---
# yamllint disable rule:line-length
name: Publish release to pypi

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read # access to check out code and install dependencies

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    concurrency:
      group: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv pip install -e .[release]

      - name: Build
        run: flit build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
