---
# yamllint disable rule:line-length
name: Publish release to pypi

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    concurrency:
      group: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        if: ${{ !env.ACT }} # skip during local actions testing
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[release]

      - name: Build
        run: flit build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
